### ISSUE TITLE
hyperslab: merge subset definitions or pass a "list" of offsets? 

### ISSUE THREAD

**Issue by fmarionpoll** [Apollo3zehn/HDF5.NET#17]
Hi all,

does anyone knows how to merge different hyperslab definitions? I am working with 2D data (1028 channels x 3 10e6 points sampled along time) which are chunked (n=200). I can read 1 channel at a time and thanks to effort from Apollo3zehn and the use of threads, we can read this within a reasonable time (4 s instead of 30-40 s). However, I'd like to read a user-defined subset of these channels. Is it possible with the current implementation of hyperslab within HDF5.NET?  

Right now, the only way I see how to use hyperslab is to define blocks of contiguous channels (changing "count" and/or "block"), or of channels which are regularly separated (changing "stride"). As a results, it means to read 1 channel at a time. Is it possible to define a "list" of channels? 

Sorry if I missed something... And many thanks for any help (and your patience).
Fred

Here is a figure of what I would like to achieve. Right now, I see how to read one row (yellow). I'd like to be able to read at once all green rows as well.
![Untitled-1](https://user-images.githubusercontent.com/7628937/135632268-006980a0-c460-4215-a76b-77ed3ae7f8b7.gif)

**Comment by Apollo3zehn** [comment]
You are right, with a single hyperslab there is no chance to read the data as shown in your image.

The native C library supports combining hyperslabs (https://confluence.hdfgroup.org/display/HDF5/H5S_COMBINE_SELECT) but I do not know how to implement it. I have to study the C lib first.

Are your chunk dimensions 1x200? In that case the bytes are stored sequencentially in memory, I.e. [row 1, row 2, ...], which means there should be no real performance difference between a single read for all rows in question and multiple single-row reads.

**Comment by fmarionpoll** [comment]
Thank you for your comment. The chunks are 1028x200 - sorry, I was sloppy in my description. 
May be the easiest would be to read each chunk in turn and manually export a subset of the data...

**Comment by Apollo3zehn** [comment]
Currently there is a walker implementation that is based on a single hyperslab. This walker enumerates all steps required to read the dataset according to the hyperslab. I could imagine to extend the read method so that it accepts custom walkers. So there could be a HyperslabWalker and an abstract CustomWalker. The actual implementation would need to derive from that CustomWalker and enumerate the custom read steps. The reason to have a base class is because the handling of chunks is quite complex and that would be encapsulated by the base class.

In your case that would look like:

```cs
IEnumerable<Step> Walk()
{
    yield return new Step(<start coordinates 1>, length);
    yield return new Step(<start coordinates 2>, length);
    ...
}
```

A step consists of start coordinates and a length to specify the number of elements to read in the fastest changing dimension, I.e. in your case the number of elements per row.

Maybe I can test that on Monday or Tuesday.

**Comment by fmarionpoll** [comment]
Thank you, Vincent. I'll test it in the following days. Right now, I am struggling with my program to replace a single channel selection with a list of selected channels. Not that this is difficult, but it implies a cascade of user-interface small changes...

As for the logic of the reading and exporting, I had in mind that one a chunk was read, it was the whole chunk that was brought to memory. It is only the final stage of the hyperslab which extracts relevant data to memory? I was thinking about an alternative strategy which is to read "all" channels and just add one routine to extract the requested channels, doing this chunk by chunk? 

I'll compare the 2 approaches anyway.

**Comment by Apollo3zehn** [comment]
Yes, the chunk is loaded completely into memory, so if you have access to it, you can extract the data you want. But that's nearly the same approach as shown above using two walkers.

HDF5 stores chunk data in row major order. So it is the last dimension that changes fastest (within a chunk)
https://stackoverflow.com/questions/24116713/hdf5-rowmajor-or-colmajor

But that's a topic that confuses me regularly :-)

**Comment by Apollo3zehn** [comment]
There was a bug in the code above, the reused coordinates array was modified by HDF5.NET leading to wrong coordinates on the next `yield return`. Therefore I resset now all coordinates for each yield. Single-threaded loading time is about 20s. 

```cs
static void Main(string[] args)
{
    H5Filter.Register(
        identifier: H5FilterID.Deflate,
        name: "deflate",
        filterFunc: DeflateHelper_Intel_ISA_L.FilterFunc);

    var file = H5File.OpenRead(@"C:\Users\wilvin\Downloads\Trace_20210715_16_54_48_1mM(+++).raw.h5");
    var dataset = file.Dataset("sig");
    var sw = Stopwatch.StartNew();

    var cols = 3_000_000UL;
    var chunkCols = 200UL;
    var rows = 6UL;
    var totalElementCount = cols * rows;

    // dataset (source)
    IEnumerable<Step> SourceWalker(ulong[] limits)
    {
        var coordinates = new ulong[2]; // reuse array to reduce GC pressure

        for (var i = 0UL; i < cols; i += chunkCols)
        {
            coordinates[1] = i;

            coordinates[0] = 2; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 5; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 6; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 12; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 15; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 16; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
        }
    }

    var datasetSelection = new DelegateSelection((ulong)totalElementCount, SourceWalker);

    // memory (target)
    IEnumerable<Step> TargetWalker(ulong[] limits)
    {
        var coordinates = new ulong[2]; // reuse array to reduce GC pressure

        for (var i = 0UL; i < cols; i += chunkCols)
        {
            coordinates[1] = i;

            coordinates[0] = 0; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 1; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 2; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 3; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 4; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
            coordinates[0] = 5; coordinates[1] = i; yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
        }
    }

    var memorySelection = new DelegateSelection(totalElementCount, TargetWalker);

    // read (option 1, convenient)
    var memoryDims = new[] { rows, cols };

    var result = dataset
        .Read<ushort>(
            fileSelection: datasetSelection,
            memorySelection: memorySelection,
            memoryDims: memoryDims
        ).ToArray2D((int)rows, (int)cols);

    Console.WriteLine(sw.Elapsed);
                
    // read (option 2, avoid ToArray2Dcopy operation)
    //var result2 = dataset
    //    .Read<int>(
    //        fileSelection: datasetSelection,
    //        memorySelection: memorySelection,
    //        memoryDims: memoryDims
    //    );

    //var channel1 = result2.AsSpan().Slice(cols * 0, cols);
    //var channel2 = result2.AsSpan().Slice(cols * 1, cols);
}
```

**Comment by fmarionpoll** [comment]
Thanks. I could indeed compile the dev version and insert in my program your reading routine example. Good news: it works. I read the same data as before.

When reading 9 channels at a time, it takes about 14 s, while this takes 42 s in my program. However, reading a single channel is still 14 s for the new reading method (which was expected) but only 4 s with the multithreaded earlier version. 

So far, I do not have more precise measurements, because this combined reading approach uncovered a default in my programming that I need to fix first (each time a change is made to the list of selected channels is made, it triggers a read :( ).

Bottom line: thumbs up to you, Vincent!!!!

PS For the record, the selected channels are stored in a dictionary, with the key= channel selected and the value= ushort[]. Here is the current reading routine. 

public static void A13ReadAllDataFromChannels(ChannelsDictionary dataSelected)
        {
            var h5Dataset = H5FileRoot.Group("/").Dataset("sig");
            var cols = h5Dataset.Space.Dimensions[1];
            const ulong chunkCols = 200;
            var rows = (ulong) dataSelected.Channels.Count;
            var totalElementCount = cols * rows;
            //var nchunks = (long)(1 + cols / chunkCols);

            int ndimensions = h5Dataset.Space.Rank;
            if (ndimensions != 2)
                return;

            // dataset (source)
            IEnumerable<Step> SourceWalker(ulong[] limits)
            {
                var coordinates = new ulong[2];

                for (var i = 0UL; i < cols; i += chunkCols)
                {
                    foreach (var (key, _) in dataSelected.Channels)
                    {
                        coordinates[0] = (ulong) key; 
                        coordinates[1] = i; 
                        yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
                    }
                }
            }

            var datasetSelection = new DelegateSelection(totalElementCount, SourceWalker);

            // memory (target)
            IEnumerable<Step> TargetWalker(ulong[] limits)
            {
                var coordinates = new ulong[2];

                for (var i = 0UL; i < cols; i += chunkCols)
                {
                    coordinates[1] = i;
                    for (int j = 0;  j < dataSelected.Channels.Count; j++)
                    {
                        coordinates[0] = (ulong) j;
                        coordinates[1] = i;
                        yield return new Step() { Coordinates = coordinates, ElementCount = chunkCols };
                    }
                }
            }

            var memorySelection = new DelegateSelection(totalElementCount, TargetWalker);

            var memoryDims = new[] { rows, cols };

            var result2 = h5Dataset
                .Read<ushort>(
                    fileSelection: datasetSelection,
                    memorySelection: memorySelection,
                    memoryDims: memoryDims
                );

            var index = 0;
            var icols = (int) cols;
            foreach (var (key, _) in dataSelected.Channels)
            {
                dataSelected.Channels[key] = result2.AsSpan().Slice(icols * index, icols).ToArray();
                index++;
            }
        }

**Comment by Apollo3zehn** [comment]
I am not sure what you mean with "When reading 9 channels at a time, it takes about 14 s, while this takes 42 s in my program.". Which approach takes 14 seconds and which one takes 42 s? :-)

**Comment by Apollo3zehn** [comment]
4 seconds are very good, I am happy to hear that :-)

**Comment by Apollo3zehn** [comment]
I can check it on Monday in case you do not find the source of the bug until then :-)

**Comment by Apollo3zehn** [comment]
Yes I will include everything we have tested here. But I need to write some tests and documentation for it first. Right now I am working on a different project, when that is done, I will continue here. I hope its not a too big problem for you to depend on the dev branch until then. Here is the full list of changes I need to verify first: https://github.com/Apollo3zehn/HDF5.NET/pull/19/files

**Comment by fmarionpoll** [comment]
Ugh! many things to do on your side! 
(no problem on my side with working with the dev branch - was just wondering). 

Take care!
